### ISSUE TITLE
Cocoapod build issue

### ISSUE THREAD

**Issue by noahemmet** [tenonedesign/T1Autograph#1]
Hi! I'm running into an error when I try to build to the simulator using the `1.6.2` cocoapod. Interestingly, building to the device works fine.

The error:

```
duplicate symbol _llvm.cmdline in:
    /Users/noahemmet/Documents/Simple/Mobile-iOS/Pods/T1Autograph/libT1Autograph.a(T1DrawingView.o)
    /Users/noahemmet/Documents/Simple/Mobile-iOS/Pods/T1Autograph/libT1Autograph.a(T1AutographPopup.o)
duplicate symbol _llvm.embedded.module in:
    /Users/noahemmet/Documents/Simple/Mobile-iOS/Pods/T1Autograph/libT1Autograph.a(T1DrawingView.o)
    /Users/noahemmet/Documents/Simple/Mobile-iOS/Pods/T1Autograph/libT1Autograph.a(T1AutographPopup.o)
ld: 16 duplicate symbols for architecture x86_64
```

(There's actually a bunch of those for a bunch of `.o` files).

I'm curious if this is maybe one of two things:
1. Perhaps `ONLY_ACTIVE_ARCH`  is set to `YES`?
2. I noticed that in the `Podfile.lock`, under the "PODS" header, `T1Autograph` points to `1.6.2`, while under the "DEPENDENCIES" header, it points to `1.6.1`. A cursory glance through the rest of the pods shows matching version numbers.

**Comment by tenonedesign** [comment]
Hello,

Sorry to hear you had trouble building.  Thank you for reporting the errors.

This release includes LLVM bitcode embedded within the binary, and may therefore cause linker errors in Xcode versions lower than 7.  A special version with bitcode stripped out is available here:  https://tenonedesign.com/media/T1Autograph-1.6.2-no-bitcode.zip

If your duplicate symbol messages are caused by something else, please let us know, and thanks again.

**Comment by noahemmet** [comment]
That worked, thanks so much! Any plans to re-introduce an Xcode 6-compatible cocoapod before 7 exits beta?

**Comment by tenonedesign** [comment]
Probably not, although it would be nice if workarounds were not necessary.  Perhaps next year we will make the transition in two version steps.  The first step compatible with the old Xcode version and the new OS, and the second step optimized for new Xcode version and the new OS.  The podfile would allow for selection of the best version for a particular build environment.
