### ISSUE TITLE
Dynamic framework needed

### ISSUE THREAD

**Issue by zaubara** [tenonedesign/T1Autograph#2]
Hi,

are there any plans to release the library as a dynamic framework, possibly with carthage support? Static libraries are a thing of the past and should be replaced for quite some time now.

Thanks

**Comment by tenonedesign** [comment]
Thanks for the request.  The static library route can be a bit tiresome.  T1Autograph supports iOS versions older than 8.  When that is no longer the case we’ll look at updating the distribution mechanism.  Carthage support is a good idea.  The latest T1Autograph version and information can be found at https://tenonedesign.com/t1autograph.php.

**Comment by zaubara** [comment]
Thanks for your quick response! It is, especially because we use private frameworks that depend on the plugin; having the plugin in two frameworks results in ugly warnings and uncertainties.
If you're dedicated to releasing the plugin as a dynamic framework, I would suggest releasing two versions, so you can keep supporting iOS older than 8. In most cases, this just means adding a second scheme on a different target (ie. the dynamic framework target), usually the same code runs fine in both.

For carthage support, since your library is closed source, you might want to look into "Archive prebuilt frameworks into one zip file" in the Carthage readme for additional ease of use.

**Comment by tenonedesign** [comment]
Thank you for the followup info.  If you'd like to test the current version of T1Autograph bundled as a dynamic framework, email devs@ our url and we will send you a build.
