### ISSUE TITLE
Get crashed if point count is less than 50 in iOS => 9.0 

### ISSUE THREAD

**Issue by pradeepdaffodil** [tenonedesign/T1Autograph#3]
Hi I am using paid license since 1.5 years but now is not working with iOS 9 and above. it get crashed if signature point count is less than 50, and also some times it crashed with unrecognised selectors.

> Tested on iPad 2/iPad 4 (4th generation with iOS 9.0 and 9.3)

**Comment by tenonedesign** [comment]
Thanks for the report!  Could you contact the support email address for T1Autograph?  The email is devs@ our domain (tenonedesign.com).  We should be able to get this resolved for you quickly.

It would help to include the T1Autograph build number you’re using.  It can be logged with a statement like NSLog(@"autograph version: %d",(int)self.autograph.buildNumber);
